apiVersion: v1
kind: Service
metadata:
  name: openvasd
  labels:
    {{- include "openvasd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq .Values.openvasd.tls.certificates.deploy_server true }}
      targetPort: 443
      {{ else }}
      targetPort: 80
      {{ end }}
      protocol: TCP
      name: http
    {{- if eq .Values.vulnerabilityservices.enabled true }}
    - port: {{ .Values.vulnerabilityservices.gsa.service.port }}
      targetPort: 9392
      protocol: TCP
      name: gsa
    {{ end }}
  selector:
    {{- include "openvasd.selectorLabels" . | nindent 4 }}
